name: Spatie test suite

on: [push]

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v1

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Execute tests (Unit and Feature tests) via PHPUnit
                run: vendor/bin/phpunit

    style:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v1

            -   name: Fix style
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --config=.php_cs --allow-risky=yes --dry-run

            -   name: Commit report
                run: |
                    git config --global user.name 'Spatie bot'
                    git config --global user.email 'commit-bot@spatie.be'
                    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                    git diff-index --quiet HEAD || git commit -am "Fix styling"
                    git push
