name: Test

on: [push]

jobs:
    test:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [ 7.2, 7.3]
                laravel: [5.8.*, 6.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 6.*
                        testbench: 4.*
                    -   laravel: 5.8.*
                        testbench: 3.8.*


        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            -   run: echo ${{ toJSON(matrix.dependencies)}}

            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Require Laravel & Testbench
                run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

            -   name: Install dependencies
                run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Setup PHP
                uses: nanasess/setup-php@master
                with:
                    php-version: ${{ matrix.php }}

            -   name: Execute tests
                run: vendor/bin/phpunit
