name: Test

on: [push, pull_request]

jobs:
    test:

        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php: [ '7.2', '7.3',]

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Setup PHP
                uses: nanasess/setup-php@master
                with:
                    php-version: ${{ matrix.php }}

            -   name: Execute tests
                run: vendor/bin/phpunit
